### ISSUE TITLE
project rename?

### ISSUE THREAD

**Issue by nrdxp** [lf-/nix-doc#18]
I was going to start a similar project a few months back, but started a new gig and haven't had any time to work on it. I'd like to offer up the name I was using for that repo (which I never published). The reason I suggest this is because the current name is dangerously similar to the (seemingly) abandoned [nixdoc](https://github.com/nix-community/nixdoc) making discoverability difficult.

So I propose the name `dox`

**Comment by lf-** [comment]
I'm not interested in renaming this project in general as I understand this project appears higher in search and is relatively clear it's separate based on its description. I'm also not a particular fan of that name:

* it's not clearly associated with Nix
* it has extremely unfortunate denotation outside of computing: it's used to refer to the practice of nonconsensual publishing of (especially marginalized people's) private details as a silencing tactic

**Comment by nrdxp** [comment]
No worries just a suggestion, as I'm not going to be using it anymore. Thanks for this awesome project :pray:
