### ISSUE TITLE
sha256 mismatch while building from default.nix

### ISSUE THREAD

**Issue by akirak** [lf-/nix-doc#6]
`cargoSha256` in `default.nix` seems to mismatch the current snapshot. I am unable to install the program using nix now.

**Comment by akirak** [comment]
Possibly fixed by #5, but do you need `fetchGit` in `src = builtins.fetchGit ./.;`? If you use `src = ./.`, the sha will be different.

**Comment by akirak** [comment]
The use of gitignore would be a good idea. You can use `niv` to manage dependencies. [nix-hello-world](https://github.com/DamienCassou/nix-hello-world/) is a good example.

**Comment by lf-** [comment]
@akirak I believe I have fixed that issue now as I've been testing. And I tried to use Niv but ran out of motivation since this tool inherently cannot pin nixpkgs due to its dependency on the system Nix version and I didn't want to figure out how to not do so.

**Comment by lf-** [comment]
I have fixed both this and the thing I was complaining about in my comment so they will never happen again by rewriting our nix expressions :)

**Comment by akirak** [comment]
Thanks, it's a great work!
